### ISSUE TITLE
[master] Connection reset by peer

### ISSUE THREAD

**Issue by iBezneR** [JoeAlisson/async-mmocore#7]
[pool-9-thread-1] ERROR io.github.joealisson.mmocore.ReadHandler - Connection reset by peer
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:395)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:191)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
	at java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:306)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)

**Comment by iBezneR** [comment]
[pool-9-thread-1] WARN io.github.joealisson.mmocore.Client - java.io.IOException: Connection reset by peer
java.util.concurrent.ExecutionException: java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.CompletedFuture.get(CompletedFuture.java:69)
	at io.github.joealisson.mmocore.Connection.writeSync(Connection.java:68)
	at io.github.joealisson.mmocore.Connection.write(Connection.java:52)
	at io.github.joealisson.mmocore.Client.write(Client.java:97)
	at io.github.joealisson.mmocore.Client.close(Client.java:128)
	at net.sf.l2j.gameserver.network.L2GameClient.closeNow(L2GameClient.java:478)
	at net.sf.l2j.gameserver.network.L2GameClient.onBufferUnderflow(L2GameClient.java:650)
	at net.sf.l2j.gameserver.network.clientpackets.L2GameClientPacket.read(L2GameClientPacket.java:40)
	at io.github.joealisson.mmocore.ReadHandler.execute(ReadHandler.java:116)
	at io.github.joealisson.mmocore.ReadHandler.parseAndExecutePacket(ReadHandler.java:110)
	at io.github.joealisson.mmocore.ReadHandler.onCompleteRead(ReadHandler.java:69)
	at io.github.joealisson.mmocore.ReadHandler.readData(ReadHandler.java:62)
	at io.github.joealisson.mmocore.ReadHandler.completed(ReadHandler.java:37)
	at io.github.joealisson.mmocore.ReadHandler.completed(ReadHandler.java:13)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:158)
	at java.base/sun.nio.ch.Invoker.invoke(Invoker.java:186)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:273)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:298)
	at java.base/java.nio.channels.AsynchronousSocketChannel.read(AsynchronousSocketChannel.java:425)
	at io.github.joealisson.mmocore.Connection.read(Connection.java:39)
	at io.github.joealisson.mmocore.ConnectionHandler$AcceptConnectionHandler.acceptConnection(ConnectionHandler.java:117)
	at io.github.joealisson.mmocore.ConnectionHandler$AcceptConnectionHandler.completed(ConnectionHandler.java:93)
	at io.github.joealisson.mmocore.ConnectionHandler$AcceptConnectionHandler.completed(ConnectionHandler.java:87)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
	at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:158)
	at java.base/sun.nio.ch.Invoker.invoke(Invoker.java:186)
	at java.base/sun.nio.ch.UnixAsynchronousServerSocketChannelImpl.onEvent(UnixAsynchronousServerSocketChannelImpl.java:193)
	at java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:306)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implWrite(UnixAsynchronousSocketChannelImpl.java:701)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:383)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:388)
	... 32 more

**Comment by JoeAlisson** [comment]
Fixed on 78c0a26617f3a260ad7bbe9f06e85a891749af84
